# Maps are the recommended as a safer way to use "if" statements
# (google "nginx if is evil") because it's not evaluated during
# request processing.
# https://www.getpagespeed.com/server-setup/nginx/nginx-if-is-evil
# https://bjornjohansen.com/tag/nginx/

map $cookie_token $cookie_exists {
    default 1;
    ""      0;
}

server {
    listen 80;
    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* ^/(home|game-settings|lobby|waiting-room|replay|profile|settings)$ {
        if ($cookie_exists = 0) {
            return 302 '/login';
        }
        try_files $uri $uri/ /index.html;
    }
  
    location ~* ^/(login|register|register-success)$ {
        if ($cookie_exists = 1) {
            return 302 '/home';
        }
        try_files $uri $uri/ /index.html;
    }

    location /v1/ {
        proxy_pass http://backend:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
        proxy_connect_timeout 60;

    }

    location /ws/ {
        proxy_pass http://backend:3001/;
        rewrite ^(\/ws/*)$ $1 break;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
        proxy_connect_timeout 60;
    }
}
