services:
  backend:
    build: backend
    image: ttt_backend
    env_file:
      - backend/postgres/postgres.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    restart: always
  database:
    build: backend/postgres
    image: ttt_database
    env_file:
      - backend/postgres/postgres.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5432:5432"
      # only exposed as long as postgres is the only container
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always

secrets:
    db_password:
      file: ./secrets/postgres-passwd

volumes:
  postgres_volume:
